//
// Created by Skyler Arnold on 8/20/23.
//

#ifndef YACHE_SQUARESTATE_HPP
#define YACHE_SQUARESTATE_HPP


enum SquareState {
    EMPTY,
    WHITE_PAWN,
    WHITE_EN_PASSANT_TARGET,
    WHITE_ROOK,
    WHITE_KNIGHT,
    WHITE_BISHOP,
    WHITE_KING,
    WHITE_QUEEN,


    BLACK_PAWN,
    BLACK_EN_PASSANT_TARGET,
    BLACK_ROOK,
    BLACK_KNIGHT,
    BLACK_BISHOP,
    BLACK_KING,
    BLACK_QUEEN
};


#endif //YACHE_SQUARESTATE_HPP
